- platform: template
  sensors:
    kr_km_electric:
      friendly_name: Kr. pr. km på el
      value_template: '{{ ((states.sensor.charge_price_low.state.split(" ")[-1].replace("kr","") | float(0)) / 40) | round(2) }}'
      device_class: monetary
      unit_of_measurement: 'kr'
    kr_km_fuel:
      friendly_name: Kr. pr. km på benzin
      value_template: '{{ ((states.sensor.ok_blyfri_95.state.replace(",",".") | float(0)) / 20) | round(2) }}'
      device_class: monetary
      unit_of_measurement: 'kr'