######################################
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

######################################
# HTTP setup for allowing reverse-proxy
http:
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.254.254.9
    - 172.16.201.2
    - 172.30.33.0/24
    - 192.168.1.190
  ip_ban_enabled: false
  login_attempts_threshold: 5

######################################
# Home Assistant setup
homeassistant:
  customize: !include customize.yaml
  #customize_glob: !include_dir_merge_named configurations/customize_glob
  packages: !include_dir_merge_named configurations/packages/
  allowlist_external_dirs:
    - /config/www/rest
    - /config

######################################
# Frontend setup
frontend:
  themes: !include_dir_merge_named themes

######################################
# Default includes
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

######################################
# Integrations without configuration
media_extractor:
wake_on_lan:

######################################
# Configurations
binary_sensor: !include_dir_merge_list configurations/binary_sensor
conversation: !include configurations/conversation.yaml
device_tracker: !include configurations/device_tracker.yaml
fuelprices_dk: !include configurations/fuelprices.yaml
group: !include_dir_merge_named configurations/groups
intent_script: !include_dir_merge_named configurations/intent_script
media_player: !include_dir_merge_list configurations/media_player
powercalc: !include configurations/powercalc.yaml
proximity: !include_dir_named configurations/proximity
pyscript: !include configurations/pyscript.yaml
recorder: !include configurations/recorder.yaml
rest: !include_dir_merge_list configurations/rest
rest_command: !include configurations/rest_command.yaml
sensor: !include_dir_merge_list configurations/sensor
shell_command: !include configurations/shell_commands.yaml
switch: !include_dir_merge_list configurations/switch
template: !include_dir_merge_list configurations/template
tts: !include configurations/tts.yaml
zha: !include configurations/zha.yaml

# logger:
#   default: warning
#   logs:
#     homeassistant.components.person: debug
