################################
#  Monitor certificate expiry  #
#                              #
# When about to expire, notify #
# mobile device belonging to   #
# Morten                       #
################################

sensor:
  - platform: template
    sensors:
      home_certificate_expiry_days:
        friendly_name: "Home certificate expiry days"
        unit_of_measurement: 'dage'
        value_template: >
          {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_home_trab_dk'), 0) - as_timestamp(states.sensor.date.last_updated, 0)) / 86400) | int }}
        icon_template: >-
          {% if ((as_timestamp(states('sensor.cert_expiry_timestamp_home_trab_dk'), 0) - as_timestamp(states.sensor.date.last_updated), 0) / 86400) | int > 31 %}
            mdi:check
          {% else %}
            mdi:alert-octagram
          {% endif %}
      home_certificate_expiry_date:
        friendly_name: "Home certificate expiry date"
        value_template: >
          {{ as_timestamp(states('sensor.cert_expiry_timestamp_home_trab_dk'), 0) | timestamp_custom('%d/%m-%Y') }}
        icon_template: >-
          {% if ((as_timestamp(states('sensor.cert_expiry_timestamp_home_trab_dk'), 0) - as_timestamp(states.sensor.date.last_updated), 0) / 86400) | int > 31 %}
            mdi:certificate
          {% else %}
            mdi:certificate-outline
          {% endif %}

      wildcard_certificate_expiry_days:
        friendly_name: "Wildcard certificate expiry days"
        unit_of_measurement: 'dage'
        value_template: >
          {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_admin_trab_dk'), 0) - as_timestamp(states.sensor.date.last_updated, 0)) / 86400) | int }}
        icon_template: >-
          {% if ((as_timestamp(states('sensor.cert_expiry_timestamp_admin_trab_dk'), 0) - as_timestamp(states.sensor.date.last_updated), 0) / 86400) | int > 31 %}
            mdi:check
          {% else %}
            mdi:alert-octagram
          {% endif %}
      wildcard_certificate_expiry_date:
        friendly_name: "Wildcard certificate expiry date"
        value_template: >
          {{ as_timestamp(states('sensor.cert_expiry_timestamp_admin_trab_dk'), 0) | timestamp_custom('%d/%m-%Y') }}
        icon_template: >-
          {% if ((as_timestamp(states('sensor.cert_expiry_timestamp_admin_trab_dk'), 0) - as_timestamp(states.sensor.date.last_updated), 0) / 86400) | int > 31 %}
            mdi:certificate
          {% else %}
            mdi:certificate-outline
          {% endif %}

automation:
  - alias: "Alert - Home certificate expiry"
    id: certExpiryHome
    trigger:
      platform: template
      value_template: '{{ states.sensor.home_certificate_expiry_days.state|float < 14}}'
    condition:
      - condition: template
        value_template: "{{ states('sensor.home_certificate_expiry_days') != 'unknown' }}"
    action:
      - service: notify.mobile_app_mtopnord2
        data:
          message: Home SSL certifikat udløber om {{ states.sensor.home_certificate_expiry_days.state }} dage
    mode: single
  - alias: "Alert - Wildcard certificate expiry"
    id: certExpiryWildcard
    trigger:
      platform: template
      value_template: '{{ states.sensor.wildcard_certificate_expiry_days.state|float < 14}}'
    condition:
      - condition: template
        value_template: "{{ states('sensor.wildcard_certificate_expiry_days') != 'unknown' }}"
    action:
      - service: notify.mobile_app_mtopnord2
        data:
          message: Home SSL certifikat udløber om {{ states.sensor.wildcard_certificate_expiry_days.state }} dage
    mode: single
