substitutions:
  node_name: water_valve
  device_verbose_name: "Water Valve"
  board: nodemcuv2
  platform: ESP8266
  log_level: INFO

packages:
  wifi: !include common/wifi.yaml
  logger: !include common/logger.yaml

esphome:
  friendly_name: ${device_verbose_name}
  name: ${node_name}
  build_path: ./build/${node_name}
  platform: ${platform}
  board: ${board}
  esp8266_restore_from_flash: true
  
api:
  reboot_timeout: 1h
  encryption:
    key: "ykst7UIy4eBjz3NW+eZH64Shr83IAvx+Fv/PjGCXQRo="

ota:
  safe_mode: true
  password: "Cg43v3kbRHcuZP"

text_sensor:
  - <<: !include common/text_sensor/uptime.yaml

sensor:
  - <<: !include common/sensor/uptime.yaml
  - <<: !include common/sensor/wifi_signal.yaml

binary_sensor:
  - <<: !include common/binary_sensor/connection_status.yaml

button:
  - <<: !include common/button/restart.yaml

switch:
  - platform: gpio
    id: ch01
    pin: GPIO4 #D2
    name: "Valve"
    restore_mode: ALWAYS_OFF
    icon: mdi:water-pump
